version: '3.8'

services:
  # API Gateway with hot-reload
  api-gateway:
    volumes:
      - ./platforms/syla/core/api-gateway:/app
      - api-gateway-target:/app/target
      - api-gateway-registry:/usr/local/cargo/registry
    command: cargo watch -x run
    environment:
      CARGO_HOME: /usr/local/cargo
      RUST_BACKTRACE: 1

  # Execution Service with hot-reload
  execution-service:
    volumes:
      - ./platforms/syla/core/execution-service:/app
      - execution-service-target:/app/target
      - execution-service-registry:/usr/local/cargo/registry
    command: cargo watch -x run
    environment:
      CARGO_HOME: /usr/local/cargo
      RUST_BACKTRACE: 1

volumes:
  api-gateway-target:
  api-gateway-registry:
  execution-service-target:
  execution-service-registry: